# Generated by Django 3.2.8 on 2021-10-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('movie', 'movie'), ('tv-show', 'tv-show')], max_length=7)),
                ('source', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('movie', 'movie'), ('tv-show', 'tv-show')], default='movie', max_length=7)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
                ('actors', models.CharField(max_length=300)),
                ('trailer', models.CharField(max_length=300)),
            ],
        ),
    ]
