# Generated by Django 3.2.8 on 2021-10-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
